# Generated by Django 3.0.8 on 2020-07-03 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ('name',), 'verbose_name': 'Branch', 'verbose_name_plural': 'Branch'},
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='bank_name',
            new_name='bank',
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='branch',
            new_name='name',
        ),
    ]
